version: "3.1"

services:
  reconwithme-stage:
    container_name: SolShow-staging
    hostname: SolShow-staging
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
        - IMG=14
        - LOCATION=SolShow-staging
    restart: always
    user: root:root
    env_file:
      - ./.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - COMPOSE_PROJECT_NAME=SolShow-staging
    ports:
      - ${PORT}:${PORT}
